# This is a basic workflow to help you get started with Actions

name: pytest

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      # Install Python
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Setup MPI
        uses: mpi4py/setup-mpi@v1
         
      - name: Run tests with pytest
        run: pytest 

      # Runs a single command using the runners shell
      - name: pytest
        run: pytest --cov=delta --junitxml=test_results.xml tests
      - name: Upload pytest test results
        uses: actions/upload-artifact@v2
        with:
          name: pytest-results
          path: test_results.xml 
        if: ${{ always() }}
